version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - jaru-api_app-network

  cej_scraping:
    build:
      context: .
      dockerfile: python/Dockerfile
    container_name: cej_scraping
    networks:
      - jaru-api_app-network
    env_file:
      - python/app/.env  
    environment:
      - DATABASE_URL=mysql://root:jaruapi@jaru-api-mysql-1:3306/jaru_cej
      - API_KEY=tu_api_key_aquí
      - API_KEY_NAME=X-API-KEY
    depends_on:
      - selenium

networks:
  jaru-api_app-network:
    driver: bridge